name: 'Dependabot Batcher'

on: workflow_call

jobs:
  dependabot-batcher:
    name: 'Combine Dependabot PRs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPENDABOT_BATCH_TOKEN }}

      - name: 'Set Node Version'
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.nvmrc'

      - name: 'Dependabot Batcher'
        uses: Legal-and-General/dependabot-batcher@v1.0.4
        with:
          token: ${{ secrets.DEPENDABOT_BATCH_TOKEN }} #required
          baseBranchName: 'master'
