name: Dependabot Batcher Scheduled
on:
  schedule:
    - cron:  '0 9 * * 1,3'

jobs:
  # Batches Dependabot PRs into one by merging them into a combined branch, then raising a new PR
  dependabot-batcher:
    name: 'Combine Dependabot PRs (Scheduled)'
    uses: ./.github/workflows/dependabot.reusable.yml
    secrets: inherit
